# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sY-MCv5Wau5XP01-14_6p52ArMDNNI4P

# Install Libraries
"""

!pip install pandas Sastrawi nlp-id

"""# Import Libraries"""

import pandas as pd

"""# Load data"""

df = pd.read_csv('/content/kompas-Jan29-2022.csv')

df.head()

"""# Text Lowering"""

text = "Selamat datang di Online Bootcamp Python dengan tema Data Mining."

text = text.lower()

text

def text_lowering(text):
    return text.lower()

"""You can try to lower all the text in dataframe"""

df["lower_judul"] = df["judul"].apply(text_lowering)

df.info()

df.head()

df["lower_kategori"] = df["kategori"].apply(text_lowering)

df.head()

# df[column_name][:5]

"""# Remove Numbers, Special Characters, and Extra Spaces

Menghilangkan angka[0-9], karakter spesial [~!@#$%^&*()_+{{}|":?><,./';], dan spasi tambahan
"""

text = "Selamat12 datang di()  Online Bootcamp; (!7Python dengan-- tema__Data~@Mining"

import re

# remove numbers
text = re.sub(r'[0-9]+', '', text)
text

# remove special characters
text = re.sub(r'[^\w\s]', '', text)
text

# remove underscore
text = text.replace("_", " ")
text

text_list = text.split()
text_list

texted = " ".join(text_list)
texted

# remove extra spaces
text = " ".join(text.split())
text

def normalisasi(text):
    text = re.sub(r'[0-9]+', '', text)
    text = re.sub(r'[^\w\s]', '', text)
    text = " ".join(text.split())
    return text

df["normalisasi"] = df["lower_judul"].apply(normalisasi)

df[["lower_judul","normalisasi"]][10:20]

"""Let's try into the dataframe"""

# df = ...

"""# Stopword Removal

Menghilangkan kata-kata yang tidak bermakna seperti kata hubung, kata ganti orang, dan sejenisnya.
"""

text = "Selamat datang di Online Bootcamp Python dengan tema Data Mining. Apa kabar kalian semua?"

"""- Library Sastrawi"""

from Sastrawi.StopWordRemover.StopWordRemoverFactory import StopWordRemoverFactory, StopWordRemover, ArrayDictionary

# get list of stopwords
stopword_list = StopWordRemoverFactory().get_stop_words()

stopword_list[:10]

# create stopwords instance
factory = StopWordRemoverFactory()
stopwords = factory.create_stop_word_remover()

text = stopwords.remove(text)

text

text= text.lower()

"""Add new stopwords into existed stopwords"""

# create a new list of stopwords
new_stopwords = ['apa', 'selamat', 'kalian']

# add both stopwords 
all_stopwords = stopword_list + new_stopwords

# create ArrayDictionary 
stopword_dict = ArrayDictionary(all_stopwords)

sastrawi_stopwords = StopWordRemover(stopword_dict)



text = sastrawi_stopwords.remove(text)
text

"""- Library NLP ID"""

from nlp_id.stopword import StopWord

# create instance stopword
stopword = StopWord() 
stopword.get_stopword()

text = "Selamat datang di Online Bootcamp Python dengan tema Data Mining. Apa kabar kalian semua?"

text = stopword.remove_stopword(text)
text

"""Let's try into dataframe"""

def remove_stopword_with_sastrawi(text):
    text = sastrawi_stopwords.remove(text)
    return text

df["remove_stopword_with_sastrawi"] = df["normalisasi"].apply(remove_stopword_with_sastrawi)

before_stopword = df['normalisasi'][10]
after_stopword = df['remove_stopword_with_sastrawi'][10]
print(before_stopword)
print(after_stopword)

def remove_stopword_with_nlp(text):
    text =  stopword.remove_stopword(text)
    return text

df["remove_stopword_with_nlp"] = df["normalisasi"].apply(remove_stopword_with_nlp)

before_stopword = df['normalisasi'][2]
after_stopword = df['remove_stopword_with_nlp'][2]
print(before_stopword)
print(after_stopword)

df['lower_judul'][2]

"""# Text Stemming

Menghilangkan imbuhan yang terdapat pada kata-kata dalam sebuah kalimat.

- Library Sastrawi
"""

from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

# create stemmer
factory = StemmerFactory()
stemmer = factory.create_stemmer()

# text stemming
text = "berbahagialah di hari yang menyenangkan ini!"
text = stemmer.stem(text)
text

def text_steming(text):
    text = stemmer.stem(text)
    return text

"""Let's try into dataframe"""

df["stemmed"]= df['remove_stopword_with_sastrawi'].apply(text_steming)

df["remove_stopword_with_sastrawi"][2]

df['stemmed'][2]

!pip install swifter

import swifter

df['stemmed'] = df['remove_stopword_with_sastrawi'].swifter.apply(text_steming)

df["remove_stopword_with_sastrawi"][2]

df['stemmed'][2]

"""# Text Lemmatizing

Mengubah kata menjadi bentuk bakunya

- Library NLP ID
"""

from nlp_id.lemmatizer import Lemmatizer

lemmatizer = Lemmatizer()

text = 'Saya sedang mencoba untuk belajar penambangan data menggunakan python.'
text = lemmatizer.lemmatize(text)

text

"""Let's try into dataframe"""

def text_lemmatizing(text):
    text = lemmatizer.lemmatize(text)
    return text

df['lemmatized']=df['remove_stopword_with_nlp'].swifter.apply(text_lemmatizing)

df['remove_stopword_with_nlp'][1210]

df['lemmatized'][1210]

df.head()

